### ISSUE TITLE
Consider mentioning lead-ins and their treatment

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#15]
Originally written by @martinpub

The guidelines currently do not mention any specific handling of lead-ins, e.g. capitalization of the first few words at the start of the chapter. Is this something we should cover maybe?

We were discussing if preservation of this capitalization could be annoying for Braille readers. On the other hand, the capitalization cue could be valuable for sighted readers so there might be a case for preserving it also.

What do you think?

Comment by @josteinaj

I think it would be a good idea to mention it. In my opinion, the capitalization should be done using CSS, while the underlying text should not be capitalized.

I'm not sure how easy this is for external producers in all cases though. Can they be sure which characters should still be capitalized? For instance "MY NAME IS JOSTEIN" should be "My name is Jostein" and not "My name is jostein", "NATO" should not be "nato" etc.

Comment by @martinpub 

Yes, agreed, could be styled with CSS if needed.

Very good point on how to make such a rule work in a production context. Very often it requires language knowledge, what are abbrev., proper nouns, etc. Perhaps it is not possible to fix without manual inspection upon delivery.

MTM discussed this and we believe correcting lead-in capitalization should be added to a delivery check/editing at the ordering agency, if we add this.

Another thing to note is that the scope might be bigger than just lead-ins, at least when it comes to braille production. Another example is headings. It will probably be difficult to introduce "decapitalization" to headings as well though, as it will considerably increase the number of items to manually check/edit in this regard. But wanted to mention it for now.

**Comment by martinpub** [comment]
@AndersEkl @jonaslil What did we decide on this? Should be add a class just to identify lead-ins, and perhaps also capitalised headings? This could provide for more easy access in automated post processing.

/Martin, Linda, Oscar

**Comment by jonaslil** [comment]
In the last editor's meeting, we discussed the issue of normalizing capitalized text and I think we agreed to suggest this should be done by suppliers, at least in the draft that we send out for comments. We still have doubts, though, on how the suppliers will handle this. I don't think we decided if a class should be added or not.

Some thoughts:

- Usually it is clear from other cues where the chapter starts, so a lead in at this place is an embellishment that does not add any information. We don't need to preserve such layout features in the epub.
- Adding a class to the lead in would be useful espcecially if the supplier does the normalization ("decapitalization"), to identify the places that need to be checked. And it would be useful if the ordering agency want's to preserve the styling.
- I'm a bit unsure about adding a class to headings also. Though it would be a way to find the places where the supplier has changed capitalization. What kind of automated post processing are you thinking about?

By the way I like the instructions @TorilBWM posted above. Are they for suppliers or for internal use?

**Comment by jonaslil** [comment]
I did an update e9d722e to get this issue going, and assigned it to myself because I have the related #61. Please feel free to comment or add directly to the text.

The text I wrote suggests a class for lead-ins but not for other cases of all caps. Judging from the comments above, we should (also) have a class that just identifies normalized uppercase text for QA or automated normalisation. Should this general class be applied to lead-ins as well? Note that we can´t use the same class for cases where we want to preserve uppercase styling (or small caps, which lead-ins usually are) and for cases where the styling is not to be preserved. The simplest solution would then be to apply the general class and get rid of lead-in styling.

Other questions:

Do we want to apply normalization to text captured from images? Uppercase text is very common there. But this text will be edited for the image description anyway.

Another specific case is uppercase words or phrases that appear in body text, as a way of suggesting emphasis, quotes from printed sources or similar. I think they need to be preserved, at least through CSS. So either we normalize them but give them a separate class, or then we exclude them from normalization.

**Comment by AndersEkl** [comment]
I don't think we want them to do anything inside the body text, except for lead-ins. I don't think it is necessary to do any normalization of captured text from images, either.

**Comment by jonaslil** [comment]
Rewrote the section in commit 2da04f0, please review and comment if further changes are needed.
