### ISSUE TITLE
Clarify the application of backlinks when multiple references go to the same note

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#18]
Originally written by @martinpub 

Backlinks treatment for notes with multiple note references needs to be decided.

See discussion in https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/509.

Comment by @ManfredMuchenberger

We internally discussed notes with multiple note references some time ago.
In plain (non-technical) language I think we found, that:

- either the App has to handle this by storing from which note reference the user jumped to the note or
- we would have to include several copies of the same note-text (one for each note reference)

Another way for the App to handle this would be to use a pop-up window to display the note and not jump to the note.

Comment by @martinpub 

We recently had a similar title. We went for @ManfredMuchenberger's second alternative.

Comment by @josteinaj 

Sounds reasonable. Can we then implement the validation rule so that there must be exactly one reference to a note element, no more, no less?

I suppose this should probably be described in the guidelines? Can we implement this without updating the guidelines (for now)?

Also, can there be notes with no references? For instance if the author forgot to add the reference, or deleted the sentence containing the reference?

Comment by @martinpub 

> Sounds reasonable. Can we then implement the validation rule so that there must be exactly one reference to a note element, no more, no less?

I think this is reasonable.

> I suppose this should probably be described in the guidelines? Can we implement this without updating the guidelines (for now)?

Yes it should be clarified. I think it would be OK to implement even before updating the guidelines, but maybe @AndersEkl and more people should add their views, I'm not able currently to work with developments and possibly not even a 100 percent up to date on the time line.

> Also, can there be notes with no references? For instance if the author forgot to add the reference, or deleted the sentence containing the reference?

In this case, I think it would be up to the Ordering Agency to insert the implied noteref location? And if just a note with no intented ref position, perhaps the note markup is not the best fit, but rather a regular aside text-box interpretation would be better?

Comment by @josteinaj 

Ok, then let's implement a rule saying "all notes must have exactly one note reference". We'll update the guidelines later.

Comment by @AndersEkl 

I can see no problem with enforcing this rule. There could potentially be situations where this rule prevents us from capturing the exact way notes are done in the source material, but then we should probably change it anyway to a more standard solution for usability purposes. We can add that to the to-do-list for next guidelines revision.

**Comment by martinpub** [comment]
See also #29

**Comment by AndersEkl** [comment]
Any comments on the re-written notes section, or shall I close those issues? @martinpub @jonaslil @oscarlcarlsson

**Comment by martinpub** [comment]
Haven't had time yet to check, sorry.

**Comment by jonaslil** [comment]
I think the re-written text about note markup is very good.

The only thing I see some problems with is the requirement to repeat notes in order to have unique backlinks. This may work in many cases, but I suspect it is not a universally applicable solution. I have seen online articles where note references are used to link to a numbered reference list, where every item is a single publication. Repeating items in a reference list would be confusing for anyone trying the navigate it as a list. But there will always be edge cases that we can't cover in the guidelines.

Another problem is that repeating a note will affect the note numbering if the notes are an ordered list without hard coded numbers, which is now the default solution. The repeated note texts would not have the same number anymore, and all following notes would get the wrong number. Maybe we can get around this by using divs instead of list items in such cases?

Another thing: I think the English text for the note section heading should be just "Notes", not "End notes". I looked at some books and that is what you usually see.

Two spelling edits: which ever -> which ever, end notes -> endnotes.

**Comment by AndersEkl** [comment]
I thought we had a discussion about this (repeating note texts) at one of our meetings and concluded it as the best option?

**Comment by jonaslil** [comment]
Sorry, I don't remember all the details and I hadn't encountered the example I mention above at that time.

We should just go for this solution in the guidelines. The issue with note numbering still needs to be handled.

**Comment by AndersEkl** [comment]
I can add some text about using divs when having to repeat numbers.
