### ISSUE TITLE
Backlink markup needs clarification

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#29]
Originally written by @martinpub 

"3.4.7 Notes and Note References" refers to the [Accessible Publishing Knowledge Base](http://kb.daisy.org/publishing/docs/html/notes.html) for how to format notes and note references.

In the examples from the KB, they use different constructions for the backlink text/link, for regular footnotes the backlink text is in the `@title` of the link element, and the note number is being used as link text content. In the endnote example, however, the note number is handled by correct itemisation in the parent `<ol>`, and the backlink text is used as the link text content.

Currently the first example could be an issue in talking book production, where regular text content is preferable over attribute text for synchronised narration purposes.

Another complicating aspect of the first example construction is in DAISY 2.02 back conversion, where backlinks are probably going to be removed (because the linking control is transferred to the SMIL files). If the note number and the backlinks are not separated, there is a risk that the note number is lost.

My question is, should we rather require "regular backlinks", as in the second (endnote) examples?

Comment by @AndersEkl 

Yes, I agree with using "regular" backlinks.

**Comment by AndersEkl** [comment]
The issue is more or less solved by the current version of the guidelines, but the wording needs to be more precise.

**Comment by jonaslil** [comment]
Ideally, the backlink text would include the note number, as suggested in the Daisy KB, [example 5](http://kb.daisy.org/publishing/docs/html/notes.html#ex-05). In Swedish for example "Gå till notreferens 1.", not just "Gå tillbaka till notreferensen." Otherwise, we will have lots of links with the same accessible name.

**Comment by martinpub** [comment]
Perhaps the backlinks should be moved to precede the note text? The DAISY KB makes a point in [example 4](http://kb.daisy.org/publishing/docs/html/notes.html#ex-04) that placing the backlink first in the note makes the user aware of it.

**Comment by jonaslil** [comment]
I think this is an option worth considering. But I suppose that would mean using only the note number as backlink text. That is how backlinks are handled in most publisher epubs. How do you see this in relation to the back conversion and talking book production issues mentioned above?

On the other hand, even if the backlink is after the note text in a separate paragraph, I think users will pretty fast learn where to find them. 

I think this needs to be considered in relation to a broader issue about note mark up. Especially endnote markup is left somewhat open in the current guidelines. Referring to the Daisy KB is not enough, since you find two conflicting versions there: one using lists (Example 2), and another using divs as containers for the notes (example 5). In a sample book by MTM, I saw that list mark up was used, but with the auto numbering hidden and the list number hard coded in the beginning of the note. That would allow for using the (hard coded) number as backlink. Otherwise, numbered lists are hard to reconcile with backlinks as in Example 4.

As to my earlier comment about including the note number in the backlink text, I'm not quite shure this is necessary if it complicates production. The backlinks are probably used only in the context of reading the note, where the note number is present. So I would say WCAG 2.4.4 Link Purpose (In Context) is satisifed with the current back link text. 2.4.9 Link Purpose (Link Only) is not, but that is level AAA.

**Comment by martinpub** [comment]
Thanks @jonaslil for your input. I think that Link Purpose (In Context) should be enough. The links will seldom be used as accessed from a screen reader's list of links, etc, they will be used for the user to go back to the body when they have read the footnote.

So my suggestion is the clarification will be to specify in the Nordic Guidelines how to mark up backlinks, by putting them at the end of the note using a general text reference.

**Comment by martinpub** [comment]
Not at all!
