### ISSUE TITLE
Update the contents of accessibility metadata

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#53]
There has been some changes in how accessibility metadata are to be specified. We need to update the guidelines accordingly.

**Comment by jonaslil** [comment]
This commit contains a draft of a new version of the metadata section:  67cfc53 Any suggestions for improving it are welcome @martinpub @AndersEkl @oscarlcarlsson

**Comment by AndersEkl** [comment]
I haven't read it yet, but I removed a faulty character in a url that precented conversion of the markdown file. I pushed a corrected file to the repo. I will read through the section now.

**Comment by AndersEkl** [comment]
Looks good to me!

**Comment by martinpub** [comment]
I think your text is fine @jonaslil, however, can we perhaps soften the "also required are" bit? I would like to add something about the default is for the producer to add it, but acknowledge that some ordering agencies will likely want to skip it, due to their internal workflows. At MTM we will likely produce a11y metadata internally in post production, and having to deal with overwriting existing such data is possible but even better not ordering it in the first place.

Perhaps a note and a pointer to agency-specific guidelines is sufficient.
