### ISSUE TITLE
Clarification regarding <strong> and <em>-markup

### ISSUE THREAD

**Issue by oscarlcarlsson** [nlbdev/nordic-accessible-epub-guidelines#57]
The section regarding `<strong>` and `<em>` needs to be adjusted.

"Please take care that text marked up with em or strong is identical with the original book. Do not include space or punctuation which is not emphasised in the original. Words in em or strong at the end of sentences should not include end-of-sentence punctuation, like full stops, unless the whole sentence is emphasised. If a sentence ends with an emphasised word, and the next sentence begins with a new emphasised word, make sure the words are marked up using separate instances of em or strong, and that the end-of-sentence punctuation is not included."

If this is a longer section of `<em>` one continuous string marked up with it is easier to read in braille.

**Comment by jonaslil** [comment]
Should we remove this sentence from the current guidelines: "Do not include space or punctuation which is not emphasised in the original"?

If the emphasised passage consists of several whole sentences it should go without saying that they are merged into one em or strong element. Other than that, the possibility of merging seems limited to cases where the only thing separating the emphasised words are spaces and punctuation within a sentence. Do we want an explicit rule stating that? Or could it be recommendation rather than a strict requirement? Applying such a rule strictly would probably mean more manual work in some cases.

We can't merge empahsised parts of one sentence with emphasised parts of another sentence. This would result in incorrect nesting when sentence markup is applied.

**Comment by oscarlcarlsson** [comment]
Our current sentence-markup splits the em up for each sentence if there are more than one sentence in the same `<em>`.
this:  
`<p><em>Uppmärkning` av kursiv stil kan ligga över två meningar. Här kommer ett `exempel.</em></p>`

becomes:
`          <span class="sentence">
            <em>Uppmärkning av kursiv stil kan ligga över två meningar.</em>
          </span>
          <span class="sentence">
            <em>Här kommer ett exempel.</em>
          </span>`

**Comment by jonaslil** [comment]
The issue was discussed in the editor's meeting. We think current text is adequate, no revision needed.
