### ISSUE TITLE
position of image captions

### ISSUE THREAD

**Issue by oscarlcarlsson** [nlbdev/nordic-accessible-epub-guidelines#60]
In the  2020-1 guidelines, image captions are only allowed before images. Maybe we should consider allowing image captions before and after images and let the specific agencies decide the order? For synced audio, the screen position may vary between different reading systems. By allowing both we can add some flexibility between agencies depending on which reading system we use.

**Comment by josteinaj** [comment]
I think there should at least be a default that should be used, unless the ordering agency specifies otherwise.

**Comment by oscarlcarlsson** [comment]
Absolutely. There might not be anything else needed than an "unless instructed otherwise"-comment and allowing it in the validation.

**Comment by jonaslil** [comment]
I agree that both positions should be allowed and that it is good to have a default. By the way, what is the reasoning behind the current instruction to move captions up above the image? A better reading order between caption and alt text?

**Comment by oscarlcarlsson** [comment]
Not sure, actually. @martinpub do you know?
Wouldn't it be better to have it the other way if we want a better reading order between alt text and caption?

**Comment by martinpub** [comment]
I can't remember, maybe @AndersEkl does. To me, caption first is natural, it is kind of a heading to an image.

**Comment by AndersEkl** [comment]
There was an issue with HTML validity, if I remember correctly. Inside the `<figure>` element there are restrictions on where to place an `<aside>` element. Our previous pattern, having the image tag followed by caption and then description was not valid. This is how I remember it, but I might be wrong. There was a reason for having this order, at least.

**Comment by josteinaj** [comment]
It might also have to do with image series, and being able to determine if a caption belongs to an image or the image series. Also might be related to DTBook validity when converting.

**Comment by AndersEkl** [comment]
I just tested in Oxygen... The folowing is invalid html:
```<figure>
<img src="whatever.jpg" alt="whatever"/>
<figcaption>Whatever</figcaption>
<aside>...</aside>
</figure>```
Whereas the following is valid:
```<figure>
<figcaption>Whatever</figcaption>
<img src="whatever.jpg" alt="whatever"/>
<aside>...</aside>
</figure>```
If there is an `<aside>` present inside the `<figure>` element there cannot be anything between `<img>` and `<aside>`.

**Comment by AndersEkl** [comment]
And, obviously, this is also valid:
```
<figure>
<img src="whatever.jpg" alt="Whatever"/>
<figcaption>Whatever</figcaption>
</figure>
```
So, it is the `<aside>` that is limiting how elements can be placed in relation to each other.

**Comment by martinpub** [comment]
Great find @AndersEkl!

**Comment by AndersEkl** [comment]
Unless we change the solution completely, I think this order of elements needs to stay as it is. We can't have invalid html.

**Comment by jonaslil** [comment]
Noting that this issue is linked to #4, and the  [Best Practices for Authoring Extended Descriptions in EPUB](https://daisy.github.io/transitiontoepub/best-practices/extended-desc/ExtendedDescriptionsBestPractices.html) referenced there.

Our current solution for image descriptions limits where you can place the figcaption because of the html rule that a figcaption has to be the first or the last element of the figure. Replacing the aside with another tag would not help. The position is the problem.

A simple solution would be to move the aside out of the figure, immediately after it. Accidentally, I recently made a book like that (an Indesign-based pilot book). The figcaptions were below the images. No Epubcheck validation issues. Obviously, this would require adjustements in the epub-DTBook conversion scripts.

**Comment by martinpub** [comment]
Thanks for linking these issues @jonaslil. I don't like having the aside outside the figure wrapper, but I now that this is one of the proposed ways currently.

I suggest we leave this open as dependent on #4.

**Comment by AndersEkl** [comment]
We discussed the alternative of placing the `<aside>` outside the `<figure>` element when we did the 2020-1 guidelines but decided against it back then.

**Comment by oscarlcarlsson** [comment]
I had a look at http://kb.daisy.org/publishing/docs/html/images-desc.html
they have an example where they add the aside inside the figcaption. doing it that way allows the figcaption to be the last element in the figure tag while including image description.

**Comment by jonaslil** [comment]
Coming back to this issue: In the example in the Daisy KB with an aside inside the figcaption, the aside is hidden. Since we don't do hidden descriptions, this method seems problematic.

I'm still curious about why the image description has to be inside the figure element. As long as we have aria-describedby (or aria-details), there is a programmatic link between image and description in any case.

**Comment by martinpub** [comment]
> I'm still curious about why the image description has to be inside the figure element. As long as we have aria-describedby (or aria-details), there is a programmatic link between image and description in any case.

I don't think there is a strong opposition, just a semantic fåfänga on my end at least ;). The programmatic link is there alright.

**Comment by AndersEkl** [comment]
Closing this, as it is handled in #4 .
