### ISSUE TITLE
Handling bridgeheads

### ISSUE THREAD

**Issue by AndersEkl** [nlbdev/nordic-accessible-epub-guidelines#66]
Bridgeheads are deprecated and we should remove this from the document. It may be mentioned in several places. There is, for instance, a paragraph about it in the "Poetry and Verse" section.

This is mentioned in #27 , but I thought it might be good to make it a separate issue.

**Comment by josteinaj** [comment]
You mean remove the use of the deprecated vocabulary value, or remove bridgeheads completely? Isn't there a lot of cases where we want structurally unimportant headings? There is a lot of them in newspapers, but probably also in magazines.

**Comment by AndersEkl** [comment]
I mean remove the use of the bridgehead value. It needs to be handled some other way, of course.

**Comment by martinpub** [comment]
Having read through the discussions here and in #27, I think there are three alternatives:

1. Keep using `@epub:type bridgehead` despite its deprecation in EPUB SSV.
2. Using `h[x]` headings but perhaps with relaxing the rule of having all those in the nav toc (this could be accomplished by assigning them a class, so that they could be excluded from validation cross-reference checks, [as suggested by Jonas](https://github.com/nlbdev/nordic-accessible-epub-guidelines/issues/27#issuecomment-2060684423)).
3. Use some other markup that is none of the above. Maybe `<p class="bridgehead">` or similar. (I believe adding `@role="heading"` will effectively be similar to `h[x]` headings.)

I think I vote for 2. 3 or 1 could be useful if we believe that we, or rather external producers, will not always be able to determine the correct level, but I'm not sure that is the case?

**Comment by oscarlcarlsson** [comment]
I think that keeping them as <p> with a heading role sounds good. It's probably the easisest rule to follow as well.

**Comment by jonaslil** [comment]
I'm not sure about the heading role. The use case would be when the level can't be determined. But normally, `role="heading"` is complemented with a level attribute. If you don't specify the level, [it defaults to 2](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/heading_role) and [this is what screen readers convey](https://a11ysupport.io/tests/tech__aria__heading-role-no-level).

**Comment by AndersEkl** [comment]
TODO: Define a class for headings that exclude them from the nav file. Define a class to make `<p>` into a "fake" heading and describe use cases for text boxes, poetry etc.

**Comment by AndersEkl** [comment]
In the section about text boxes there is a paragraph about bridgehead being deprecated. Do we need that if we now have a specified other solution? @martinpub @jonaslil @oscarlcarlsson @lindheli

**Comment by martinpub** [comment]
Either remove it, or refer to the new solution for "fake headings"?

**Comment by AndersEkl** [comment]
Yeah, I'll remove it and replace it with the solutions we agreed upon yesterday. The class name will be "faux-hd", by the way. :)

**Comment by martinpub** [comment]
Great work Anders!

**Comment by jonaslil** [comment]
Agree, great work! A question:

The general rule for poems, stated at the beginning, is to wrap them in `<div class="verse">`. Later on, it is said `section` should be used if the poem is given an h# heading. Should this section have `class="verse"` as well, to distinguish poems from other types of sections? It might be good for styling purposes.

**Comment by AndersEkl** [comment]
@jonaslil Great idea! I will add this and then close this issue.
